[package]
name = "toy-blockchain-cli"
version = "0.1.0"
authors = ["Collins Muriuki <murerwacollins@gmail.com>"]
edition = "2018"

[bin]
name = "toy_bc"
path = "src/main.rs"

[[lib]]
name = "toy_bc_lib"
path = "src/lib/lib.rs"


[dependencies]
time = "*"
serde = "*"
serde_derive = "*"
sha2 = "*"
